/**
 * ClickHouse Cluster Composition (build-time topology constructor)
 *
 * `makeClickHouseCluster(topology)` separates the two halves of a CHI
 * honestly:
 *
 * - BUILD-TIME topology (`zones`, `replicas`, `shards`, `keeper` presence,
 *   user names/networks) is fixed when the composition is CONSTRUCTED. The
 *   zone-pinned layout enumerates pod templates and per-replica entries, so
 *   it can never be instance-dynamic (the operator's own `podDistribution`
 *   supports only the hostname topologyKey — Altinity/clickhouse-operator
 *   issue #772 — and EBS volumes are zonal, so replicas must be pinned).
 *
 * - RUNTIME spec (`name`, `namespace`, `version`, `storage`, `clusterName`,
 *   keeper host, per-user password hashes) flows through as schema proxies
 *   and serializes to clean CEL in kro mode.
 *
 * Same construction pattern as `makeCaddyIngress`: build-time options select
 * the resource/schema shape statically — no runtime `includeWhen`
 * conditionals, no accepted-but-ignored spec fields.
 */

import { type } from 'arktype';
import { kubernetesComposition } from '../../../core/composition/imperative.js';
import { Cel } from '../../../core/references/cel.js';
import type { CallableComposition } from '../../../core/types/deployment.js';
import type { Composable } from '../../../core/types/index.js';
import { containsKubernetesRefs } from '../../../utils/type-guards.js';
import { configMap } from '../../kubernetes/config/config-map.js';
import { serviceAccount } from '../../kubernetes/rbac/service-account.js';
import {
  type ClickHouseClusterSpec,
  ClickHouseClusterStatusSchema,
  type ClickHouseClusterStatus,
  type ClickHouseClusterTopology,
  type ClickHouseInstallationConfig,
  type ClickHouseS3StorageOptions,
  type ClickHouseStorageTopology,
  type ClickHouseUser,
} from '../types.js';
import { clickHouseInstallation, DEFAULT_CHI_CLUSTER_NAME } from '../resources/installation.js';
import { clickHouseS3BackupCronJob } from '../resources/s3-backup.js';
import {
  ClickHouseS3PlainRewritableVersionSchema,
  IRSA_ROLE_ARN_ANNOTATION,
  isS3Storage,
  type ResolvedClickHouseS3Storage,
  resolveClickHouseStorage,
} from '../utils/s3-storage.js';
import {
  assertPositiveIntegerCount,
  ClickHouseClusterNameSchema,
} from '../utils/validation.js';

/** Native (TCP) ClickHouse port — operator default ChDefaultTCPPortNumber. */
export const CLICKHOUSE_NATIVE_PORT = 9000;
/** HTTP interface port — operator default ChDefaultHTTPPortNumber. */
export const CLICKHOUSE_HTTP_PORT = 8123;
/** Default Keeper/ZooKeeper client port — operator default KpDefaultZKPortNumber. */
export const CLICKHOUSE_KEEPER_PORT = 2181;
/** Default database exposed on the status contract. */
export const CLICKHOUSE_DEFAULT_DATABASE = 'default';
/** Default allowed source networks for declared users. */
export const DEFAULT_USER_NETWORKS_IP = ['::/0'] as const;

/** Default ResourceGraphDefinition name generated by the cluster composition. */
export const DEFAULT_CLICKHOUSE_CLUSTER_RGD_NAME = 'clickhouse-cluster';

/** Default KRO kind generated by the cluster composition. */
export const DEFAULT_CLICKHOUSE_CLUSTER_KIND = 'ClickHouseCluster';

/** Resource id of the CHI inside the composition graph. */
const CHI_RESOURCE_ID = 'clickhouse';

/** Resource id of the IRSA ServiceAccount inside the composition graph. */
const S3_SERVICE_ACCOUNT_RESOURCE_ID = 'clickhouseS3ServiceAccount';

/** Resource id of the scheduled S3 backup CronJob. */
const S3_BACKUP_RESOURCE_ID = 'clickhouseS3Backup';

/**
 * Resource id of the CONTRACT ConfigMap inside the composition graph.
 *
 * WHY THIS RESOURCE EXISTS. Several fields of the declared status contract —
 * the default database, the first declared user, the native port, and the whole
 * `storage` durability block — come from the CONSTRUCTION-TIME topology, not
 * from the owned CHI. As bare constants they were dropped by KRO (status CEL
 * cannot express a literal-only leaf, nor reference `schema.spec.*`), so the
 * declared schema promised fields the live CR never carried: a GitOps consumer
 * running `kubectl get clickhouseclusters -o yaml` saw readiness and endpoints
 * but no durability contract, which is the one thing it most needs to know.
 *
 * Writing them into a ConfigMap this composition OWNS gives them a resource to
 * be projected from, so every declared field appears on the live instance
 * status in both factory modes. The ConfigMap is useful in its own right — it
 * is the cluster's durability contract in a readable place — and it is a graph
 * child, so it is created and deleted with the instance.
 *
 * @see https://github.com/yehudacohen/typekro/issues/188
 */
const CONTRACT_RESOURCE_ID = 'clickhouseContract';

/** Suffix of the contract ConfigMap's name (`<installation>-contract`). */
export const CLICKHOUSE_CONTRACT_CONFIGMAP_SUFFIX = '-contract';

/**
 * Normalized build-time topology (defaults applied once, at construction).
 */
interface ResolvedTopology {
  zones: readonly string[];
  replicas: number;
  shards: number;
  keeper: boolean;
  /**
   * Render the scheduled backup as `BACKUP ... ON CLUSTER`. True whenever a
   * single-host statement would produce a PARTIAL backup (>1 shard or replica)
   * or a keeper is available to coordinate the fan-out.
   */
  onClusterBackup: boolean;
  users: readonly {
    name: string;
    networksIp: readonly string[];
    credentialSource: 'sha256' | 'secret';
  }[];
  /** Build-time storage topology, resolved and validated once. */
  storage: ClickHouseStorageTopology;
  /** The raw S3 options, narrowed — present iff the topology selects S3. */
  s3Options?: ClickHouseS3StorageOptions;
  /** The S3 resolution, present iff the topology selects object storage. */
  s3?: ResolvedClickHouseS3Storage;
}

function resolveTopology(topology: ClickHouseClusterTopology): ResolvedTopology {
  const replicas = topology.replicas ?? 1;
  const shards = topology.shards ?? 1;
  // Fail at CONSTRUCTION time (not first serialization): counts are
  // build-time topology, and zero/fractional/negative counts compile to
  // invalid operator input (`replicasCount: 0` / `shardsCount: 0`).
  assertPositiveIntegerCount('makeClickHouseCluster', 'replicas', replicas);
  assertPositiveIntegerCount('makeClickHouseCluster', 'shards', shards);

  // Storage is build-time for the same reason zones are: the S3 branch
  // compiles to server-configuration TEXT and selects which resources exist.
  // Resolve (and reject) it at CONSTRUCTION so a bad bucket/credential shape
  // surfaces before the first serialization. The runtime `size`/`version`
  // halves are validated again by `clickHouseInstallation` inside the body.
  const storage = topology.storage ?? {};
  if (containsKubernetesRefs(storage)) {
    throw new Error(
      'makeClickHouseCluster: build-time option `storage` contains a schema/resource ' +
        'reference. The S3 disk configuration compiles into a storage_configuration XML ' +
        'document and selects resources (ServiceAccount, backup CronJob), so it is fixed at ' +
        'construction — only storage.size / storage.storageClassName are runtime spec.'
    );
  }
  const resolvedStorage = resolveClickHouseStorage('makeClickHouseCluster', storage);
  if (
    resolvedStorage.mode === 's3' &&
    resolvedStorage.diskType === 's3_plain_rewritable' &&
    replicas > 1
  ) {
    throw new Error(
      `makeClickHouseCluster: storage.diskType 's3_plain_rewritable' does not support table ` +
        `replication (ClickHouse documents mutations and replication as unsupported for the ` +
        `plain_rewritable metadata type), so it requires replicas: 1 (got ${replicas}). Use ` +
        `diskType: 's3' with storage.backup for a replicated cluster.`
    );
  }

  // Replicated tables need coordination — default keeper on for
  // multi-replica clusters unless the caller opts out explicitly.
  const keeper = topology.keeper ?? replicas > 1;

  // A DISTRIBUTED topology with a backup schedule must back up EVERY shard.
  // The only way to do that in one statement is `BACKUP ... ON CLUSTER`, and
  // that fan-out is coordinated through [Zoo]Keeper — so a multi-shard or
  // multi-replica cluster with a backup schedule and NO keeper cannot be
  // backed up completely. Fail here rather than emit a statement that
  // succeeds while capturing one shard: a partial backup that reports success
  // is worse than no backup at all.
  const distributed = shards > 1 || replicas > 1;
  if (resolvedStorage.mode === 's3' && resolvedStorage.backup !== undefined && distributed) {
    if (!keeper) {
      throw new Error(
        `makeClickHouseCluster: a topology with ${shards} shard(s) and ${replicas} replica(s) ` +
          `and a 'storage.backup' schedule requires a keeper. Backing up every shard needs ` +
          `\`BACKUP ... ON CLUSTER\`, whose fan-out is coordinated through [Zoo]Keeper; without ` +
          `one the statement would run on a single host and silently capture only that shard's ` +
          `data. Set \`keeper: true\` (and supply \`spec.keeper.host\`), or drop to ` +
          `shards: 1, replicas: 1.`
      );
    }
  }

  return {
    zones: topology.zones ?? [],
    replicas,
    shards,
    storage,
    ...(isS3Storage(storage) ? { s3Options: storage } : {}),
    ...(resolvedStorage.mode === 's3' ? { s3: resolvedStorage } : {}),
    keeper,
    // `ON CLUSTER` is rendered for every topology whose backup would otherwise
    // be partial — more than one shard or replica — and also whenever a keeper
    // is configured, because that is the topology that may GROW shards later
    // and the coordinated statement is correct for one host too.
    onClusterBackup: distributed || keeper,
    users: (topology.users ?? []).map((user) => ({
      name: user.name,
      networksIp: user.networksIp ?? DEFAULT_USER_NETWORKS_IP,
      credentialSource: user.credentialSource ?? 'sha256',
    })),
  };
}

/**
 * Build the runtime spec ArkType schema for a resolved topology. The SHAPE of
 * the schema is a build-time product: `keeper` is required iff the topology
 * enables it, and one `users.<name>` entry (with a required password hash) is
 * required per declared user — user names are literal schema keys, never
 * dynamic path fragments.
 */
function buildSpecSchema(topology: ResolvedTopology) {
  const definition: Record<string, unknown> = {
    name: 'string',
    namespace: 'string',
    // NOT a bare `'string'` when the topology selects `s3_plain_rewritable`:
    // that disk type needs a server >= MIN_S3_PLAIN_REWRITABLE_VERSION, and in
    // kro mode `version` is a per-INSTANCE value that no construction-time
    // check can see. Carrying the floor as a `pattern=` marker takes it into
    // the RGD schema, so KRO rejects an instance that selects an older server
    // instead of the disk failing at query time on a live cluster.
    version:
      topology.s3?.diskType === 's3_plain_rewritable'
        ? ClickHouseS3PlainRewritableVersionSchema
        : 'string',
    // NOT a bare `'string'`: this value reaches ClickHouse twice — as the
    // cluster identity the operator concatenates into every generated object
    // name, and as the `ON CLUSTER '<name>'` target the backup CronJob
    // interpolates into SQL. In kro mode it is a per-INSTANCE value that no
    // build-time check can see, so the constraint travels into the RGD as a
    // `pattern=` marker and KRO rejects a bad instance before it is applied.
    'clusterName?': ClickHouseClusterNameSchema,
    storage: {
      size: 'string',
      'storageClassName?': 'string',
    },
    'podResources?': {
      'requests?': { 'cpu?': 'string', 'memory?': 'string' },
      'limits?': { 'cpu?': 'string', 'memory?': 'string' },
    },
  };

  if (topology.keeper) {
    definition.keeper = { host: 'string', 'port?': 'number.integer' };
  }

  if (topology.users.length > 0) {
    definition.users = Object.fromEntries(
      topology.users.map((user) => [
        user.name,
        user.credentialSource === 'secret'
          ? { passwordSecretRef: { name: 'string > 0', key: 'string > 0' } }
          : { passwordSha256Hex: 'string' },
      ])
    );
  }

  return type(definition as never);
}

/**
 * Construct a ClickHouse cluster composition with a FIXED topology.
 *
 * The result is a normal TypeKro composition: use it directly
 * (`factory('kro').deploy({...})`) or nest it in other compositions with
 * schema references for every runtime field.
 *
 * @example
 * ```typescript
 * const clickhouse = makeClickHouseCluster({
 *   zones: ['us-east-2a', 'us-east-2b'],  // zone-pinned replicas (EBS is zonal)
 *   replicas: 2,
 *   shards: 1,
 *   users: [{ name: 'signoz' }],          // names are build-time path fragments
 * });
 *
 * await clickhouse.factory('kro').deploy({
 *   name: 'signoz-clickhouse',
 *   namespace: 'observability',
 *   version: '25.12.5',
 *   storage: { size: '100Gi', storageClassName: 'gp3-expandable' },
 *   keeper: { host: 'keeper-signoz.observability.svc.cluster.local' },
 *   users: { signoz: { passwordSha256Hex: '...' } },
 * });
 * ```
 *
 * Downstream compositions consume the typed service contract:
 * ```typescript
 * signoz({
 *   clickhouse: {
 *     host: ch.status.clickhouse.host,
 *     port: ch.status.clickhouse.port,
 *     cluster: ch.status.clickhouse.clusterName,
 *   },
 * });
 * ```
 */
export function makeClickHouseCluster(
  topology: ClickHouseClusterTopology = {}
): CallableComposition<ClickHouseClusterSpec, ClickHouseClusterStatus> {
  const resolved = resolveTopology(topology);
  const specSchema = buildSpecSchema(resolved);
  const firstUserName = resolved.users[0]?.name;

  return kubernetesComposition(
    {
      // Overridable because the generated spec schema is a product of the
      // topology, and KRO refuses a breaking CRD update — so two different
      // topologies in one cluster need two RGD identities. See
      // ClickHouseClusterTopology.name.
      name: topology.name ?? DEFAULT_CLICKHOUSE_CLUSTER_RGD_NAME,
      kind: topology.kind ?? DEFAULT_CLICKHOUSE_CLUSTER_KIND,
      spec: specSchema as never,
      status: ClickHouseClusterStatusSchema as never,
    },
    (spec: ClickHouseClusterSpec) => {
      const clusterName = spec.clusterName ?? DEFAULT_CHI_CLUSTER_NAME;

      // Runtime credentials pair with build-time user names by LITERAL key:
      // `spec.users.<name>.passwordSha256Hex` is a plain schema path, so it
      // serializes to clean CEL. Names/networks come from the topology.
      const users: ClickHouseUser[] = resolved.users.map((user) => {
        const credential = spec.users?.[user.name] as
          | { passwordSha256Hex: string }
          | { passwordSecretRef: { name: string; key: string } };
        return {
          name: user.name,
          ...(user.credentialSource === 'secret'
            ? {
                passwordSecretRef: (
                  credential as { passwordSecretRef: { name: string; key: string } }
                ).passwordSecretRef,
              }
            : {
                passwordSha256Hex: (credential as { passwordSha256Hex: string }).passwordSha256Hex,
              }),
          networksIp: [...user.networksIp],
        };
      });

      // IRSA: the CHI pod template runs as this ServiceAccount and the disk
      // configuration uses `use_environment_credentials`, so ClickHouse's AWS
      // SDK picks up the projected web-identity token. The SA is a SEPARATE
      // resource, so the composition owns it — the low-level
      // `clickHouseInstallation()` only sets `serviceAccountName` and expects
      // the account to exist.
      const s3ServiceAccountName =
        resolved.s3?.auth.kind === 'irsa'
          ? (resolved.s3.auth.serviceAccountName ?? `${spec.name}-s3`)
          : undefined;
      if (resolved.s3?.auth.kind === 'irsa' && s3ServiceAccountName !== undefined) {
        const _s3ServiceAccount = serviceAccount({
          id: S3_SERVICE_ACCOUNT_RESOURCE_ID,
          metadata: {
            name: s3ServiceAccountName,
            namespace: spec.namespace,
            annotations: {
              [IRSA_ROLE_ARN_ANNOTATION]: resolved.s3.auth.roleArn,
            },
            labels: {
              'app.kubernetes.io/name': 'clickhouse',
              'app.kubernetes.io/component': 's3-storage',
              'app.kubernetes.io/managed-by': 'typekro',
            },
          },
        });
      }

      // The installation's `storage` is the build-time topology plus the two
      // runtime (ref-safe) local-volume fields. Written out rather than spread
      // through a cast so the discriminated union stays type-checked.
      const installationStorage: Composable<ClickHouseInstallationConfig>['storage'] =
        resolved.s3Options === undefined
          ? {
              size: spec.storage.size,
              storageClassName: spec.storage.storageClassName,
            }
          : {
              ...resolved.s3Options,
              size: spec.storage.size,
              storageClassName: spec.storage.storageClassName,
              ...(s3ServiceAccountName !== undefined && resolved.s3?.auth.kind === 'irsa'
                ? {
                    auth: {
                      irsa: {
                        roleArn: resolved.s3.auth.roleArn,
                        serviceAccountName: s3ServiceAccountName,
                      },
                    },
                  }
                : {}),
            };

      const clickhouse = clickHouseInstallation({
        name: spec.name,
        namespace: spec.namespace,
        version: spec.version,
        clusterName,
        // BUILD-TIME topology — concrete values from the constructor.
        shards: resolved.shards,
        replicas: resolved.replicas,
        ...(resolved.zones.length > 0 ? { zones: [...resolved.zones] } : {}),
        // Runtime local-volume sizing merged with the build-time storage
        // topology. In PVC mode this is byte-for-byte today's input.
        storage: installationStorage,
        ...(users.length > 0 ? { users } : {}),
        ...(resolved.keeper
          ? {
              keeper: {
                // biome-ignore lint/style/noNonNullAssertion: the generated schema requires keeper when the topology enables it
                host: spec.keeper!.host,
                port: spec.keeper?.port ?? CLICKHOUSE_KEEPER_PORT,
              },
            }
          : {}),
        podResources: spec.podResources,
        id: CHI_RESOURCE_ID,
      });

      // Scheduled `BACKUP ... TO S3(...)`. This is what makes
      // `diskType: 's3'` durable at all — see resources/s3-backup.ts and the
      // durability table in docs/api/clickhouse/index.md.
      //
      // On a sharded or replicated topology the statement becomes
      // `BACKUP ... ON CLUSTER '<clusterName>'`, so EVERY shard contributes to
      // the one backup. `clusterName` is the same expression the CHI's cluster
      // is named after, so the two can never drift.
      if (resolved.s3?.backup !== undefined) {
        const _s3Backup = clickHouseS3BackupCronJob({
          name: spec.name,
          namespace: spec.namespace,
          version: spec.version,
          storage: resolved.s3,
          nativePort: CLICKHOUSE_NATIVE_PORT,
          ...(resolved.onClusterBackup ? { onCluster: true, clusterName } : {}),
          id: S3_BACKUP_RESOURCE_ID,
        });
        _s3Backup.dependsOn(clickhouse);
      }

      // The build-time half of the status contract, written to a resource this
      // composition owns so it can be PROJECTED into status instead of being a
      // literal KRO drops. See CONTRACT_RESOURCE_ID for why. Every value here
      // is construction-time concrete; nothing runtime is smuggled in.
      const _contract = configMap({
        id: CONTRACT_RESOURCE_ID,
        metadata: {
          name: `${spec.name}${CLICKHOUSE_CONTRACT_CONFIGMAP_SUFFIX}`,
          namespace: spec.namespace,
          labels: {
            'app.kubernetes.io/name': 'clickhouse',
            'app.kubernetes.io/instance': spec.name,
            'app.kubernetes.io/component': 'contract',
            'app.kubernetes.io/managed-by': 'typekro',
          },
        },
        // ConfigMap values are strings by definition, so the two non-string
        // status fields are projected back with `int(...)` and an `== "true"`
        // comparison below — both live-verified to resolve in kro mode (KRO
        // status CEL) and in direct mode (the cel-js reference resolver).
        data: {
          database: CLICKHOUSE_DEFAULT_DATABASE,
          nativePort: String(CLICKHOUSE_NATIVE_PORT),
          httpPort: String(CLICKHOUSE_HTTP_PORT),
          ...(firstUserName !== undefined ? { user: firstUserName } : {}),
          storageMode: resolved.s3 === undefined ? 'pvc' : 's3',
          ...(resolved.s3 !== undefined
            ? {
                storageDiskType: resolved.s3.diskType,
                storagePolicyName: resolved.s3.policyName,
                storageBucket: resolved.s3.bucket,
                // ONLY plain_rewritable keeps its metadata in the bucket, so
                // only it survives node loss without a backup.
                storageSelfDescribingBucket: String(
                  resolved.s3.diskType === 's3_plain_rewritable'
                ),
                ...(resolved.s3.backup !== undefined
                  ? { storageBackupSchedule: resolved.s3.backup.schedule }
                  : {}),
              }
            : {}),
        },
      });

      // Connection contract derived from the operator's ACTUAL naming
      // (release-0.27.1): the CR-level Service is `clickhouse-{chi-name}`
      // (type ClusterIP; pkg/model/chi/namer/patterns.go +
      // pkg/model/chi/creator/service.go), listening on native 9000 /
      // HTTP 8123 (type_host.go defaults). Per-host services
      // (`chi-{chi}-{cluster}-{shard}-{replica}`) exist too but the CR
      // service is the stable entrypoint.
      //
      // DERIVED FROM THE OWNED CHI RESOURCE (`clickhouse.metadata.*` /
      // `clickhouse.spec.*`) via NATURAL proxy access inside JS template
      // literals — NOT schema.spec.*. Two things make this the right form
      // in BOTH factory modes (typekro >= 0.24.0, which ships the #97
      // resource-metadata-proxy fix):
      //   - KRO mode: the imperative analyzer converts these template
      //     literals to KRO status CEL, and (post-#97) `clickhouse.metadata.*`
      //     resolves resource-anchored (`clickhouse.metadata.name`) instead
      //     of degrading to `schema.spec.name`, so they land on the live CR
      //     status for GitOps/KRO consumers.
      //   - direct mode: a template literal is plain JS, so direct mode's
      //     live-status re-execution evaluates it against the real resource
      //     values and hydrates a concrete string — where the old raw
      //     `Cel.expr("...literal CEL...")` strings stayed opaque markers.
      // The build-time fields (port/database/user and the whole `storage`
      // block) are projected from the OWNED contract ConfigMap rather than
      // inlined as literals, so they too land on the live CR — see
      // CONTRACT_RESOURCE_ID and ClickHouseClusterStatus.
      return {
        ready: clickhouse.status.status === 'Completed',
        phase:
          clickhouse.status.status === 'Completed'
            ? 'Ready'
            : clickhouse.status.status === 'Aborted'
              ? 'Failed'
              : 'Installing',
        clickhouse: {
          host: `clickhouse-${clickhouse.metadata.name}.${clickhouse.metadata.namespace}.svc.cluster.local`,
          // Projected from the owned contract ConfigMap, whose values are
          // strings by definition — `int(...)` converts back to the number the
          // status schema declares. Live-verified in BOTH modes: KRO status
          // CEL evaluates it (`port: 9000` on the instance CR) and the cel-js
          // reference resolver evaluates it against the live ConfigMap in
          // direct mode. It was previously a bare literal, so KRO dropped it.
          port: Cel.expr<number>(`int(${CONTRACT_RESOURCE_ID}.data.nativePort)`),
          nativeUrl: `clickhouse://clickhouse-${clickhouse.metadata.name}.${clickhouse.metadata.namespace}.svc.cluster.local:${CLICKHOUSE_NATIVE_PORT}`,
          httpUrl: `http://clickhouse-${clickhouse.metadata.name}.${clickhouse.metadata.namespace}.svc.cluster.local:${CLICKHOUSE_HTTP_PORT}`,
          // The resolved logical cluster name is IN the owned CHI
          // (configuration.clusters[0].name), so read it from there — the
          // `spec.clusterName ?? default` expression itself is schema-only
          // and would be dropped. Kept as a raw Cel.expr (not a natural
          // template literal) because this is a deep read through an optional
          // nested array (`configuration.clusters[0]`), where natural proxy
          // access needs non-null assertions that add noise without changing
          // the output. That is an ERGONOMIC choice, NOT a hydration limit:
          // being a resource-path CEL it resolves in BOTH modes on typekro
          // >= 0.24.0 — status CEL in `factory('kro')`, and the cel-js
          // reference resolver evaluates it against the live CHI in
          // `factory('direct')` (proven concrete — `'cluster'` — in the
          // integration suite). Same for keeper.* below.
          clusterName: Cel.expr<string>(`${CHI_RESOURCE_ID}.spec.configuration.clusters[0].name`),
          // Also projected from the contract ConfigMap. `Cel.expr` rather than
          // natural `_contract.data.database` access only because the
          // ConfigMap factory types its spec as `Record<string, never>` (a
          // ConfigMap has no `spec`), so `.data` is not on the Enhanced type —
          // a framework typing gap, not a hydration limitation.
          database: Cel.expr<string>(`${CONTRACT_RESOURCE_ID}.data.database`),
          ...(firstUserName !== undefined
            ? { user: Cel.expr<string>(`${CONTRACT_RESOURCE_ID}.data.user`) }
            : {}),
        },
        ...(resolved.keeper
          ? {
              keeper: {
                // Echo the keeper endpoint from the CHI's own zookeeper
                // section (resource-derived → lands in KRO status) rather
                // than from schema.spec.keeper (static → dropped). Kept as raw
                // Cel.expr for the same reasons as clusterName (deep optional
                // array read) — plus `port` must stay a number, which a
                // template literal would coerce to a string. Like clusterName,
                // these are resource-path CELs that resolve in BOTH modes
                // (cel-js evaluates them in direct mode) — not KRO-only.
                host: Cel.expr<string>(
                  `${CHI_RESOURCE_ID}.spec.configuration.zookeeper.nodes[0].host`
                ),
                port: Cel.expr<number>(
                  `${CHI_RESOURCE_ID}.spec.configuration.zookeeper.nodes[0].port`
                ),
              },
            }
          : {}),
        // Storage contract — the durability guarantee of this cluster, so a
        // consumer never has to read the CHI's XML to learn what it has.
        //
        // PROJECTED FROM THE OWNED CONTRACT CONFIGMAP, not inlined. These are
        // construction-time values, and as bare literals KRO dropped every one
        // of them: the declared schema promised a `storage` block the live CR
        // did not carry. Reading them back from a resource makes the whole
        // declared contract observable through KRO — the durability fields
        // most of all, since they are what a GitOps consumer cannot infer.
        storage: {
          mode: Cel.expr<'pvc' | 's3'>(`${CONTRACT_RESOURCE_ID}.data.storageMode`),
          ...(resolved.s3 !== undefined
            ? {
                diskType: Cel.expr<'s3' | 's3_plain_rewritable'>(
                  `${CONTRACT_RESOURCE_ID}.data.storageDiskType`
                ),
                policyName: Cel.expr<string>(`${CONTRACT_RESOURCE_ID}.data.storagePolicyName`),
                bucket: Cel.expr<string>(`${CONTRACT_RESOURCE_ID}.data.storageBucket`),
                // ConfigMap values are strings, so the boolean comes back as a
                // CEL comparison. ONLY plain_rewritable keeps its metadata in
                // the bucket, so only it survives node loss with no restore.
                selfDescribingBucket: Cel.expr<boolean>(
                  `${CONTRACT_RESOURCE_ID}.data.storageSelfDescribingBucket == "true"`
                ),
                ...(resolved.s3.backup !== undefined
                  ? {
                      backupSchedule: Cel.expr<string>(
                        `${CONTRACT_RESOURCE_ID}.data.storageBackupSchedule`
                      ),
                    }
                  : {}),
              }
            : {}),
        },
        installation: {
          // CHI identity from the owned resource (same reachability rule).
          name: `${clickhouse.metadata.name}`,
          namespace: `${clickhouse.metadata.namespace}`,
          endpoint: clickhouse.status.endpoint,
          // The operator's REAL CHI status fields are `hosts`/`hostsCompleted` — verified against
          // the installed CRD's OpenAPI schema on a live cluster. `hostsCount`/`hostsCompletedCount`
          // do not exist on the resource and made KRO reject the RGD outright ("undefined field
          // 'hostsCompletedCount'", GraphAccepted=False, state Inactive) — caught only by a LIVE
          // admission run; the CEL type-checker has no notion of the operator's real CRD schema.
          // The PUBLIC contract keeps the more explicit field names the review asked for; only the
          // CEL source reference changes.
          hostsCount: clickhouse.status.hosts,
          hostsCompletedCount: clickhouse.status.hostsCompleted,
        },
      };
    }
  ) as unknown as CallableComposition<ClickHouseClusterSpec, ClickHouseClusterStatus>;
}

/**
 * The default single-node cluster composition (1 shard, 1 replica, no zones,
 * no keeper, no declared users). See {@link makeClickHouseCluster} for
 * topology options.
 */
export const clickHouseCluster = makeClickHouseCluster();
