/**
 * Schema generation functionality for Kro ResourceGraphDefinitions
 *
 * This module converts Arktype schema definitions into Kro-compatible
 * simple schemas, and provides utility functions for generating schemas
 * from resource maps.
 */

import type { Type } from 'arktype';
import { KUBERNETES_REF_SCHEMA_MARKER_SOURCE } from '../../shared/brands.js';
import { escapeCelString } from '../../utils/cel-escape.js';
import { pascalCase } from '../../utils/string.js';
import { createCompositionContext, runWithCompositionContext } from '../composition/context.js';
import { getComponentLogger } from '../logging/index.js';
import { getMetadataField } from '../metadata/index.js';
import { createSchemaProxy } from '../references/index.js';
import type {
  KroSimpleSchemaWithMetadata,
  SchemaDefinition,
  TernaryConditional,
} from '../types/serialization.js';
import type { KroCompatibleType, KroSimpleSchema, KubernetesResource } from '../types.js';
import { separateStatusFields } from '../validation/cel-validator.js';
import { serializeStatusMappingsToCel } from './cel-references.js';

const logger = getComponentLogger('schema-defaults');
const SCHEMA_MARKER_PATTERN_SOURCE = KUBERNETES_REF_SCHEMA_MARKER_SOURCE;

function deriveResourceIdAliases(resourceId: string): string[] {
  const aliases: string[] = [];
  for (const match of resourceId.matchAll(/\d+/g)) {
    const suffix = resourceId.slice((match.index ?? 0) + match[0].length);
    if (suffix && /^[A-Z]/.test(suffix)) {
      aliases.push(suffix.charAt(0).toLowerCase() + suffix.slice(1));
    }
  }
  return aliases;
}

// ---------------------------------------------------------------------------
// Arktype JSON AST → Kro type helpers (private)
// ---------------------------------------------------------------------------

/**
 * Converts an Arktype JSON AST node into a Kro-compatible type string.
 *
 * Handles single-quoted literals, arrays, booleans, integer divisors,
 * and literal unions (→ Kro enum format).
 */
function getKroTypeFromJson(node: unknown): string {
  // Case 1: Object describing a type
  if (typeof node === 'object' && node !== null && !Array.isArray(node)) {
    const nodeObj = node as Record<string, unknown>;
    if (nodeObj.proto === 'Array' && nodeObj.sequence) {
      return `[]${getKroTypeFromJson(nodeObj.sequence)}`;
    }
    if (nodeObj.domain === 'number' && nodeObj.divisor === 1) {
      return 'integer';
    }
    // Map / Record types — arktype represents `Record<string, V>` as
    // `{ domain: "object", index: [{ signature: "string", value: V }] }`.
    // KRO SimpleSchema uses `map[string]<value-type>` notation for these.
    if (nodeObj.domain === 'object' && Array.isArray(nodeObj.index) && nodeObj.index.length === 1) {
      const indexEntry = nodeObj.index[0] as { signature?: unknown; value?: unknown };
      if (indexEntry.signature === 'string') {
        return `map[string]${getKroTypeFromJson(indexEntry.value)}`;
      }
    }
    if (nodeObj.domain === 'object' || nodeObj.required || nodeObj.optional) {
      return 'object';
    }
  }

  // Case 2: Array → union of literals
  if (Array.isArray(node)) {
    if (
      node.length === 2 &&
      node.some((branch) => branch.unit === true) &&
      node.some((branch) => branch.unit === false)
    ) {
      return 'boolean';
    }
    if (node.some((branch) => !branch || typeof branch !== 'object' || !('unit' in branch))) {
      return 'object';
    }
    const enumValues = node.map((branch) => {
      if (typeof branch.unit === 'string') {
        return branch.unit;
      }
      return String(branch.unit);
    });
    return `string | enum="${enumValues.join(',')}"`;
  }

  // Case 3: Simple string primitive
  if (typeof node === 'string') {
    if (node.includes('%')) {
      const [domain] = node.split('%');
      if (domain === 'number') return 'integer';
    }
    switch (node) {
      case 'number':
        return 'integer';
      case 'string':
      case 'boolean':
        return node;
    }
  }

  return 'string';
}

/**
 * Recursively convert an Arktype JSON AST into a nested KRO SimpleSchema object.
 *
 * KRO v0.8+ supports nested objects in SimpleSchema — child fields are defined
 * by indentation under a parent key. CEL expressions use dot notation to access
 * them (e.g., `schema.spec.cache.shards`). This preserves the nesting so the
 * schema matches the CEL paths generated by the schema proxy.
 */
function arktypeJsonToKroFields(node: unknown): Record<string, unknown> {
  const fields: Record<string, unknown> = {};

  if (!node || typeof node !== 'object') {
    return fields;
  }

  const nodeObj = node as Record<string, unknown>;
  if (!nodeObj.required && !nodeObj.optional) {
    return fields;
  }

  const required = Array.isArray(nodeObj.required) ? nodeObj.required : [];
  const optional = Array.isArray(nodeObj.optional) ? nodeObj.optional : [];
  const props = [...required, ...optional];

  for (const prop of props) {
    const childNode = prop.value;

    if (
      typeof childNode === 'object' &&
      childNode !== null &&
      (childNode.required || childNode.optional)
    ) {
      fields[prop.key] = arktypeJsonToKroFields(childNode);
    } else {
      fields[prop.key] = getKroTypeFromJson(childNode);
    }
  }
  return fields;
}

// ---------------------------------------------------------------------------
// Nullish coalescing default extraction
// ---------------------------------------------------------------------------

/**
 * Extract literal default values from `spec.field ?? literalValue` patterns
 * in a composition function's source code.
 *
 * **FAST PATH — NOT AUTHORITATIVE.** This regex-based extraction runs first
 * to catch the common case where a composition uses `spec.X ?? 'literal'`
 * with a literal right-hand side. It is intentionally conservative:
 *
 * - Both `??` and the literal must be on the same source line.
 * - The literal must be a string, number, boolean, or minified !0/!1 form.
 * - The right-hand side cannot be a constant, variable, template literal,
 *   function call, or expression involving other spec fields.
 *
 * Anything this regex misses is caught by {@link resolveDefaultsByReExecution}
 * (Phase 2), which actually executes the composition function with optional
 * fields set to `undefined` and observes the concrete resolved values. Phase 2
 * is the authoritative source; this function only exists to short-circuit
 * the common case so the heavy re-execution doesn't need to compare every
 * field for every composition.
 *
 * In KRO mode, `??` doesn't trigger for proxy objects (they're truthy).
 * Instead, we detect these patterns via fn.toString() and add
 * `| default=<value>` annotations to the KRO SimpleSchema so that KRO
 * uses the intended default when the field isn't provided in the CR.
 *
 * NOTE: `.orValue()` is NOT supported in KRO resource templates (only in
 * status CEL). Schema `| default=` is the correct mechanism for resource
 * template defaults.
 *
 * Handles:
 * - `spec.field ?? 'string'` or `spec.field ?? "string"`
 * - `spec.field ?? 123` (numbers)
 * - `spec.field ?? true/false` (booleans, including minified !0/!1)
 * - `spec.parent?.child ?? value` (optional chaining)
 */
export function extractNullishDefaults(
  fnSource: string
): Record<string, string | number | boolean> {
  const defaults: Record<string, string | number | boolean> = {};

  const pattern =
    /spec\.([\w]+(?:\??\.\w+)*)\s*\?\?\s*(?:(['"])([^'"]*)\2|(-?\d+(?:\.\d+)?)|true|false|!0|!1)(?=\s*[;,)}\n])/g;

  let match: RegExpExecArray | null = pattern.exec(fnSource);
  while (match !== null) {
    const fieldPath = match[1]?.replace(/\?\./g, '.');
    if (!fieldPath) {
      match = pattern.exec(fnSource);
      continue;
    }
    const stringValue = match[3];
    const numericValue = match[4];

    if (stringValue !== undefined) {
      defaults[fieldPath] = stringValue;
    } else if (numericValue !== undefined) {
      defaults[fieldPath] = Number(numericValue);
    } else {
      const fullMatch = match[0];
      if (fullMatch.endsWith('true') || fullMatch.endsWith('!0')) defaults[fieldPath] = true;
      else if (fullMatch.endsWith('false') || fullMatch.endsWith('!1')) defaults[fieldPath] = false;
    }
    match = pattern.exec(fnSource);
  }

  return defaults;
}

/**
 * Placeholder value passed in place of required spec fields during the
 * defaults-extraction re-execution. Any captured leaf value that IS this
 * string, CONTAINS this string as a substring (from template-literal
 * interpolation), or is NaN (from arithmetic coercion of the string) is
 * filtered out by the sentinel-detection logic in `extractDefaultsByComparison`
 * so it never gets recorded as a real schema default.
 *
 * The choice of a string (rather than a Symbol or object) is deliberate:
 *   - String concatenation preserves the token so template-literal usage
 *     produces a clearly-identifiable captured value (e.g. `"__typekro_default__-cfg"`).
 *   - Truthiness matches the real proxy behavior (proxies are truthy), so
 *     `if (spec.requiredField)` takes the same branch in both runs.
 *   - Numeric contexts coerce to NaN in both runs (proxies also coerce to
 *     NaN because functions have no numeric value), so arithmetic-derived
 *     NaN values are symmetric across runs and don't produce spurious defaults.
 *
 * If the propagation ever drifts out of this sentinel's shape (e.g. someone
 * introduces a Symbol-based sentinel), update `isSentinelDerivedValue` below
 * to match.
 */
export const REQUIRED_FIELD_SENTINEL = '__typekro_default__';

/**
 * Check whether a captured value is derived from the required-field sentinel
 * and therefore should NOT be recorded as a real schema default. Handles:
 *   - Direct sentinel or substring (template-literal propagation)
 *   - NaN (numeric-coercion propagation — both runs produce NaN symmetrically,
 *     but the defaults run's NaN must be filtered out of the defaults map)
 */
function isSentinelDerivedValue(v: unknown): boolean {
  if (typeof v === 'string') return v.includes(REQUIRED_FIELD_SENTINEL);
  if (typeof v === 'number') return Number.isNaN(v);
  return false;
}

/** Result of re-execution defaults analysis. */
interface ReExecutionResult {
  /** Resolved ?? default values for spec fields (field → value). */
  defaults: Record<string, string | number | boolean>;
  /**
   * Ternary conditional sections detected in string values.
   *
   * Each entry contains the raw truthy-branch text (with __KUBERNETES_REF__
   * markers, NOT yet converted to CEL), the falsy-branch value, and the
   * controlling spec field name. Consumers (core.ts, kro-factory.ts) convert
   * the markers to CEL and build `has(schema.spec.field) ? "truthy" : "falsy"`
   * conditionals.
   */
  ternaryConditionals: TernaryConditional[];
  /**
   * Cross-field presence chains (`a ?? b ?? 'lit'`) reconstructed by probing.
   * Each is a CEL conditional to write directly at a resource's structural path.
   * The single defaults run can only capture literal defaults, so these carry the
   * multi-field `has(...) ? ... : ...` chains it cannot express.
   */
  crossFieldOverrides: Array<{ resourceId: string; path: string[]; cel: string }>;
}

/**
 * Resolve ?? defaults by re-executing the composition function with undefined
 * for optional spec fields. This triggers ?? fallbacks naturally, resolving
 * imported constants from the closure (e.g., DEFAULT_SEARXNG_IMAGE).
 *
 * Also detects ternary conditional sections (spec.field ? section : '') by
 * comparing resource strings between proxy-run and defaults-run.
 *
 * Runs in a temporary, isolated composition context. Resource registrations
 * are contained within the temp context. However, composition functions with
 * external side effects (API calls, logging, metrics) will fire during this
 * re-execution. Composition functions should be side-effect-free beyond
 * resource creation for this mechanism to work safely.
 */
function resolveDefaultsByReExecution(
  compositionFn: (...args: unknown[]) => unknown,
  specType: Type,
  proxyResources: Record<string, KubernetesResource>
): ReExecutionResult | undefined {
  try {
    const specJson = specType.json as {
      required?: { key: string }[];
      optional?: { key: string }[];
    };
    if (!specJson) return undefined;

    const defaultsSpec: Record<string, unknown> = {};
    for (const p of specJson.required ?? []) defaultsSpec[p.key] = REQUIRED_FIELD_SENTINEL;
    for (const p of specJson.optional ?? []) defaultsSpec[p.key] = undefined;

    // Build the set of optional top-level field names. Only optional fields
    // can be ternary-controlled (required fields always have a value).
    const optionalFieldNames = new Set((specJson.optional ?? []).map((p) => p.key));

    const tempCtx = createCompositionContext('defaults-extraction');
    // The all-undefined defaults run can throw when a composition dereferences an
    // absent optional parent (`spec.settings.tier` with settings undefined). Contain
    // it: literal-default extraction is then simply empty, but cross-field probing
    // (which runs its own per-probe presence specs) must still proceed.
    try {
      runWithCompositionContext(tempCtx, () => {
        compositionFn(defaultsSpec);
      });
    } catch (defaultsRunErr) {
      logger.debug('Defaults run threw (absent optional parent?); continuing with probing only', {
        error: defaultsRunErr instanceof Error ? defaultsRunErr.message : String(defaultsRunErr),
      });
    }

    const defaults: Record<string, string | number | boolean> = {};
    const ternaryConditionals: ReExecutionResult['ternaryConditionals'] = [];
    const ternaryConditionFieldHints = extractTernaryConditionFieldHints(compositionFn.toString());

    // Match resources by RESOURCE ID rather than by insertion order. Compositions
    // that use `if (!spec.optional) { createResource(...) }` produce different
    // resource counts between runs — positional matching silently pairs
    // unrelated resources (e.g., the defaults run's auto-Secret against the
    // proxy run's Deployment) and corrupts both default extraction and
    // ternary detection. Key-based matching is robust against conditional
    // resource creation: resources present in only one run are simply skipped
    // for comparison.
    const proxyEntries = Object.entries(proxyResources) as unknown as [
      string,
      Record<string, unknown>,
    ][];
    const defaultsEntries = Object.entries(tempCtx.resources) as unknown as [
      string,
      Record<string, unknown>,
    ][];
    const defaultsMap = new Map<string, Record<string, unknown>>(defaultsEntries);

    if (proxyEntries.length !== defaultsEntries.length) {
      // Different resource counts between runs are expected when the
      // composition uses conditional `createResource` patterns — the
      // defaults run takes different branches than the proxy run.
      // Key-based matching handles this correctly, so downgrade to debug.
      logger.debug(
        'Re-execution produced a different number of resources than the proxy run — matching by resource ID',
        {
          proxyResourceCount: proxyEntries.length,
          defaultsResourceCount: defaultsEntries.length,
        }
      );
    }

    const crossFieldOverrides: ReExecutionResult['crossFieldOverrides'] = [];
    for (const [id, proxyRes] of proxyEntries) {
      const defaultsRes = defaultsMap.get(id);
      // Literal-default + ternary extraction need the defaults-run counterpart;
      // skip them when it's absent (only in the proxy run, or the defaults run threw).
      if (defaultsRes) {
        extractDefaultsByComparison(proxyRes, defaultsRes, defaults);
        extractTernaryConditionals(
          proxyRes,
          defaultsRes,
          ternaryConditionals,
          optionalFieldNames,
          ternaryConditionFieldHints
        );
      }
      // Cross-field `??` chain reconstruction is independent of the defaults run —
      // it does its own presence-probing — so it always runs.
      reconstructCrossFieldChains(
        compositionFn,
        specJson,
        id,
        proxyRes,
        defaults,
        crossFieldOverrides
      );
    }

    const hasResults =
      Object.keys(defaults).length > 0 ||
      ternaryConditionals.length > 0 ||
      crossFieldOverrides.length > 0;
    return hasResults ? { defaults, ternaryConditionals, crossFieldOverrides } : undefined;
  } catch (err) {
    // Best-effort: composition functions with undefined spec fields may throw
    // (e.g., accessing spec.nested.field without optional chaining). Log at
    // debug level for troubleshooting but don't fail schema generation.
    logger.debug('Defaults re-execution failed', {
      error: err instanceof Error ? err.message : String(err),
    });
    return undefined;
  }
}

// ---------------------------------------------------------------------------
// Cross-field presence-chain reconstruction (interprocedural via execution)
// ---------------------------------------------------------------------------
//
// The single defaults run (all optionals → undefined) captures only LITERAL
// defaults (`a ?? 'lit'`). A CROSS-FIELD chain (`a ?? b ?? 'lit'`) defeats it: the
// proxy run shows the output tracks `a`, the defaults run shows `'lit'`, so the
// comparison wrongly records `a → 'lit'` and drops `b`. We reconstruct the true
// chain by PROBING — running the composition under targeted presence combinations
// (driving the magic schema proxy so present fields emit markers and absent fields
// are `undefined`) and observing which field/literal each output path tracks. This
// executes the real composition AND any helper it calls (mutation, Object.assign,
// cross-module — all just run), so it needs no source resolution. Presence-based
// only; value-based branching inside helpers is out of scope (handled inline by the
// AST analyzer). Purely additive: emits only when a genuine multi-field chain is
// confirmed, so it never changes existing single-field/literal behavior.

const FULL_MARKER_RE = new RegExp(`^${SCHEMA_MARKER_PATTERN_SOURCE}$`);

/** A leaf classified during probing: a tracked spec field, a literal, or neither. */
type Leaf =
  | { kind: 'field'; field: string }
  | { kind: 'literal'; value: string | number | boolean }
  | { kind: 'none' };

/** Classify a single output-leaf value (marker-ref vs literal vs other). */
function classifyLeaf(value: unknown): Leaf {
  const s = typeof value === 'function' || typeof value === 'string' ? String(value) : null;
  const m = s?.match(FULL_MARKER_RE);
  const fp = m?.[1];
  if (fp?.startsWith('spec.')) return { kind: 'field', field: fp.slice('spec.'.length) };
  if (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean') {
    if (isSentinelDerivedValue(value)) return { kind: 'none' };
    return { kind: 'literal', value };
  }
  return { kind: 'none' };
}

/** Read the value at a structural path within a (proxy/probe) resource object. */
function readAtPath(obj: unknown, path: string[]): unknown {
  let cur: unknown = obj;
  for (const key of path) {
    if (cur == null || typeof cur !== 'object') return undefined;
    cur = (cur as Record<string, unknown>)[key];
  }
  return cur;
}

/** Write a value at a structural path within a resource object (no-op if missing). */
export function setAtResourcePath(obj: unknown, path: string[], value: unknown): void {
  const last = path[path.length - 1];
  if (last === undefined) return;
  let cur: unknown = obj;
  for (const key of path.slice(0, -1)) {
    if (cur == null || typeof cur !== 'object') return;
    cur = (cur as Record<string, unknown>)[key];
  }
  if (cur && typeof cur === 'object') {
    (cur as Record<string, unknown>)[last] = value;
  }
}

/** Collect every leaf in the proxy-run resource that is exactly a `spec.X` marker. */
function collectMarkerLeaves(
  node: unknown,
  path: string[],
  out: Array<{ path: string[]; field: string }>
): void {
  const c = classifyLeaf(node);
  if (c.kind === 'field') {
    out.push({ path: [...path], field: c.field });
    return;
  }
  // An embedded (non-exact) marker is a transformation, not a bare ref — skip it
  // but still recurse into structured values.
  if (Array.isArray(node)) {
    node.forEach((v, i) => collectMarkerLeaves(v, [...path, String(i)], out));
    return;
  }
  if (node && typeof node === 'object') {
    for (const key of Object.keys(node as Record<string, unknown>)) {
      collectMarkerLeaves((node as Record<string, unknown>)[key], [...path, key], out);
    }
  }
}

/**
 * Build a probe `spec`: the magic schema proxy (so any field access emits its
 * `spec.X` marker) wrapped so the dotted paths in `absent` resolve to `undefined`.
 * Driving presence this way lets a probe reveal which field a `??` chain falls
 * through to when earlier links are absent.
 */
function buildProbeSpec(specJson: unknown, absent: Set<string>): unknown {
  const root = (createSchemaProxy(specJson) as { spec: unknown }).spec;
  const wrap = (target: object, prefix: string): unknown =>
    new Proxy(target, {
      get(t, prop) {
        if (typeof prop !== 'string') return Reflect.get(t, prop);
        const full = prefix ? `${prefix}.${prop}` : prop;
        if (absent.has(full)) return undefined;
        const v = (t as Record<string, unknown>)[prop];
        const hasDeeperAbsent = [...absent].some((a) => a.startsWith(`${full}.`));
        if (hasDeeperAbsent && v && (typeof v === 'object' || typeof v === 'function')) {
          return wrap(v as object, full);
        }
        return v;
      },
    });
  return wrap(root as object, '');
}

/** Run the composition with a probe spec; return the resource matching `resourceId`. */
function runProbe(
  compositionFn: (...args: unknown[]) => unknown,
  specJson: unknown,
  absent: Set<string>,
  resourceId: string
): Record<string, unknown> | undefined {
  try {
    const ctx = createCompositionContext('cross-field-probe');
    runWithCompositionContext(ctx, () => {
      compositionFn(buildProbeSpec(specJson, absent));
    });
    return (ctx.resources as Record<string, Record<string, unknown>>)[resourceId];
  } catch {
    return undefined;
  }
}

const celField = (field: string): string => `schema.spec.${field}`;

/**
 * Presence guard for a (possibly nested) optional field — every ancestor must be
 * present too. `userDeployments.enableSubchart` →
 * `has(schema.spec.userDeployments) && has(schema.spec.userDeployments.enableSubchart)`.
 * Matches the optional-chain guard the inline analyzer emits, so a bare nested ref is
 * never read through an absent parent.
 */
function presenceGuard(field: string): string {
  const segs = field.split('.');
  return segs.map((_, i) => `has(schema.spec.${segs.slice(0, i + 1).join('.')})`).join(' && ');
}

/** Render the chain's CEL: <guard(a)> ? a : (<guard(b)> ? b : <tail>). */
function buildChainCel(chain: string[], tail: Leaf): string {
  const tailCel =
    tail.kind === 'literal'
      ? typeof tail.value === 'string'
        ? `"${escapeCelString(tail.value)}"`
        : String(tail.value)
      : tail.kind === 'field'
        ? celField(tail.field)
        : 'omit()';
  let expr = tailCel;
  let nested = false;
  for (const f of [...chain].reverse()) {
    expr = `${presenceGuard(f)} ? ${celField(f)} : ${nested ? `(${expr})` : expr}`;
    nested = true;
  }
  return `\${${expr}}`;
}

/**
 * For each `spec.X` marker leaf in the proxy-run resource, probe to reconstruct its
 * full `??` chain. When the chain has more than one field (a genuine cross-field
 * fallback the literal path can't express), emit a CEL conditional override and drop
 * the (wrong) single-literal default the comparison recorded for the head field.
 */
function reconstructCrossFieldChains(
  compositionFn: (...args: unknown[]) => unknown,
  specJson: unknown,
  resourceId: string,
  proxyRes: Record<string, unknown>,
  defaults: Record<string, string | number | boolean>,
  out: Array<{ resourceId: string; path: string[]; cel: string }>
): void {
  const leaves: Array<{ path: string[]; field: string }> = [];
  collectMarkerLeaves(proxyRes, [], leaves);

  for (const { path, field } of leaves) {
    // Probe every marker leaf. We don't pre-filter on declared optionality (the
    // arktype `.json` shape varies for complex/nested schemas): a field that isn't
    // presence-controlling simply won't change the leaf when toggled absent, leaving
    // the chain at length 1 → no emit. The `chain.length >= 2` gate below is the real
    // guard, so this stays additive while covering nested fields the optional-set misses.
    const chain: string[] = [];
    const absent = new Set<string>();
    let current = field;
    let tail: Leaf = { kind: 'none' };

    for (let step = 0; step < 8; step++) {
      chain.push(current);
      absent.add(current);
      const probeRes = runProbe(compositionFn, specJson, absent, resourceId);
      const next = classifyLeaf(readAtPath(probeRes, path));
      if (next.kind === 'field' && !chain.includes(next.field)) {
        current = next.field; // chain falls through to another field — keep going
        continue;
      }
      tail = next; // literal, a self/cyclic ref, or nothing → chain ends
      break;
    }

    // Emit ONLY for genuine cross-field chains (≥2 fields) — the thing the single
    // defaults run fundamentally cannot express. The comparison's single-literal
    // default for the head field is wrong here, so drop it and use the conditional.
    // Single-field cases (`x ?? lit`, bare optional refs) are left entirely to the
    // existing default/omit-wrapping mechanisms, so this change can't regress them.
    const [head] = chain;
    if (chain.length >= 2 && head !== undefined) {
      delete defaults[head];
      out.push({ resourceId, path, cel: buildChainCel(chain, tail) });
    }
  }
}

/**
 * Recursively compare proxy-run resource values (with __KUBERNETES_REF__ markers)
 * against defaults-run values (with resolved constants) to find field defaults.
 *
 * When a proxy value is `__KUBERNETES_REF___schema___spec.FIELD__` and the
 * corresponding defaults value is a concrete scalar, we record FIELD → value.
 */
function extractDefaultsByComparison(
  proxyVal: unknown,
  defaultsVal: unknown,
  result: Record<string, string | number | boolean>
): void {
  // KubernetesRef proxies are functions whose toString() returns a marker string.
  // Coerce to string to check for __KUBERNETES_REF__ markers.
  const proxyStr =
    typeof proxyVal === 'function' || typeof proxyVal === 'string' ? String(proxyVal) : null;

  // Only match when the proxy value IS the marker (exact, single reference).
  // If the marker is embedded inside a larger string (template literal), the
  // value is a transformation, not a default — e.g., `\`has-${spec.extra}\``
  // produces `"has-<marker>"` which is NOT a default for `extra`.
  const exactMarkerMatch = proxyStr?.match(new RegExp(`^${SCHEMA_MARKER_PATTERN_SOURCE}$`));
  const exactFieldPath = exactMarkerMatch?.[1];
  if (exactFieldPath?.startsWith('spec.')) {
    if (
      typeof defaultsVal === 'string' ||
      typeof defaultsVal === 'number' ||
      typeof defaultsVal === 'boolean'
    ) {
      // Skip values derived from the required-field sentinel — these aren't
      // real defaults. Covers: string containing the sentinel token
      // (template-literal propagation), NaN (arithmetic-coercion
      // propagation), and the sentinel itself.
      if (isSentinelDerivedValue(defaultsVal)) return;
      const fieldKey = exactFieldPath.slice('spec.'.length);
      if (fieldKey) {
        result[fieldKey] = defaultsVal;
      }
    }
    return;
  }
  // If the proxy is a string but contains the marker as part of larger content,
  // skip the defaults check (recursion into arrays/objects still applies below).
  if (proxyStr?.includes('__KUBERNETES_REF___schema___')) {
    return;
  }

  if (Array.isArray(proxyVal) && Array.isArray(defaultsVal)) {
    for (let i = 0; i < Math.min(proxyVal.length, defaultsVal.length); i++) {
      extractDefaultsByComparison(proxyVal[i], defaultsVal[i], result);
    }
    return;
  }

  if (proxyVal && typeof proxyVal === 'object' && defaultsVal && typeof defaultsVal === 'object') {
    for (const key of Object.keys(proxyVal as Record<string, unknown>)) {
      extractDefaultsByComparison(
        (proxyVal as Record<string, unknown>)[key],
        (defaultsVal as Record<string, unknown>)[key],
        result
      );
    }
  }
}

/**
 * Detect ternary conditional sections by finding markers in the proxy-run
 * string that are completely ABSENT from the defaults-run string.
 *
 * When `spec.redisUrl ? \`redis: ...\` : ''` is evaluated:
 * - Proxy run (truthy): the redis section with markers is included
 * - Defaults run (falsy): the redis section is empty — the marker is absent
 *
 * For each such "orphan" marker, we extract the surrounding section
 * (from the previous newline-at-start-of-key to the marker's end) as a
 * ternary-controlled conditional.
 *
 * Ternary test-field hints
 * ------------------------
 * Re-execution only shows that a marker-containing section disappeared;
 * it does not leave runtime metadata for the ternary TEST expression. The
 * caller supplies a best-effort map derived from the composition source so
 * common decoupled patterns can guard on the tested field:
 *
 *     spec.redisUrl ? `redis:\n  url: ${spec.redisUrl}` : ''
 *
 *     spec.enableRedis ? `redis:\n  url: ${spec.connectionString}` : ''
 *
 * If no hint is available, we fall back to the referenced field, preserving
 * the historical behavior for `spec.redisUrl ? ... ${spec.redisUrl} ...`.
 *
 * FRAGILE: this walks line-by-line through the proxy string and backs
 * through parent YAML keys by regex-matching `^\s*\w+:\s*$` and comparing
 * against a set of lines from the defaults string. It assumes the
 * composition constructs YAML-ish content directly (typically via template
 * literal) with 2-space indentation, canonical key: value syntax, and no
 * block scalars (`|`, `>`). Compositions that emit flow-style YAML, that
 * use tab indentation, that quote keys, or that assemble the string
 * through multiple splice operations will not match cleanly. The
 * extracted `proxySection` is later consumed by
 * `applyTernaryConditionalsToResources` via exact substring match — keep
 * both functions' assumptions in sync when updating either side.
 *
 * Tracked for replacement with AST-based detection in
 * https://github.com/yehudacohen/typekro/issues/57
 */
function extractTernaryConditionals(
  proxyVal: unknown,
  defaultsVal: unknown,
  result: ReExecutionResult['ternaryConditionals'],
  optionalFieldNames: Set<string>,
  conditionFieldHints: ReadonlyMap<string, string>
): void {
  const proxyStr = typeof proxyVal === 'string' ? proxyVal : null;
  const defaultsStr = typeof defaultsVal === 'string' ? defaultsVal : null;

  if (proxyStr && defaultsStr && proxyStr !== defaultsStr && proxyStr.length > defaultsStr.length) {
    // Find all __KUBERNETES_REF__ markers in the proxy string
    const markerPattern = new RegExp(SCHEMA_MARKER_PATTERN_SOURCE, 'g');
    let match: RegExpExecArray | null = markerPattern.exec(proxyStr);

    while (match !== null) {
      const fieldPath = match[1];
      if (!fieldPath?.startsWith('spec.')) {
        match = markerPattern.exec(proxyStr);
        continue;
      }
      const field = fieldPath.slice('spec.'.length);
      const conditionField = conditionFieldHints.get(field) ?? field;
      const marker = match[0];

      // Only optional fields can be ternary-controlled. Required fields always
      // have a value (the sentinel in the defaults run), so their markers are
      // always "absent" from the defaults string but they're substitutions,
      // not conditionals.
      const topLevelField = conditionField.split('.')[0];
      if (!topLevelField) {
        match = markerPattern.exec(proxyStr);
        continue;
      }
      if (!optionalFieldNames.has(topLevelField)) {
        match = markerPattern.exec(proxyStr);
        continue;
      }

      // Check if this marker is a TERNARY conditional (section absent from defaults)
      // vs a ?? fallback (same key exists with a different value in defaults).
      // Find the YAML key before the marker (e.g., `url: ` before the redisUrl marker).
      const lineStart = proxyStr.lastIndexOf('\n', match.index) + 1;
      const line = proxyStr.slice(lineStart, match.index + marker.length);
      const keyMatch = line.match(/(\w+):\s*$/)?.[1] || line.match(/^\s*(\w+):/)?.[1];
      const keyExistsInDefaults = keyMatch
        ? new RegExp(`\\b${keyMatch}\\s*:`).test(defaultsStr)
        : false;

      // If the key exists in defaults, this is a ?? fallback (handled elsewhere).
      // If the key is absent, this is a ternary conditional (section not present).
      if (!keyExistsInDefaults && !defaultsStr.includes(marker)) {
        // Extract the section containing this marker.
        // Walk backward from the marker to find the start of the conditional
        // section. Include parent YAML keys at ALL nesting levels (not just one)
        // so that `redis:\n  connection:\n    url: ${ref}` captures all three lines.
        let sectionStart = match.index;
        while (sectionStart > 0 && proxyStr[sectionStart - 1] !== '\n') {
          sectionStart--;
        }
        // Walk back through preceding blank lines
        while (sectionStart > 0 && proxyStr[sectionStart - 1] === '\n') {
          sectionStart--;
        }
        // Walk back through parent YAML keys (lines with `key:` and no value).
        // Keep walking as long as the previous line is a key-only line that
        // doesn't exist as a complete line in the defaults. Set membership
        // (not substring match) avoids false stops on coincidental substrings.
        const defaultsLines = new Set(defaultsStr.split('\n'));
        const allLines = proxyStr.slice(0, sectionStart).split('\n');
        while (allLines.length > 0) {
          const prevLine = allLines[allLines.length - 1];
          if (prevLine === undefined) break;
          const isKeyOnlyLine = /^\s*\w+:\s*$/.test(prevLine);
          const lineExistsInDefaults = defaultsLines.has(prevLine);
          if (isKeyOnlyLine && !lineExistsInDefaults) {
            sectionStart -= prevLine.length + 1; // +1 for the \n
            allLines.pop();
          } else {
            break;
          }
        }

        // Section ends after the marker
        const sectionEnd = match.index + marker.length;

        const proxySection = proxyStr.slice(sectionStart, sectionEnd);

        // Verify the section, when removed from proxy string, makes it closer to defaults
        if (proxySection.includes(marker)) {
          result.push({
            proxySection,
            falsyValue: '',
            conditionField,
          });
        }
      }
      match = markerPattern.exec(proxyStr);
    }
    return;
  }

  // Recurse into arrays and objects
  if (Array.isArray(proxyVal) && Array.isArray(defaultsVal)) {
    for (let i = 0; i < Math.min(proxyVal.length, defaultsVal.length); i++) {
      extractTernaryConditionals(
        proxyVal[i],
        defaultsVal[i],
        result,
        optionalFieldNames,
        conditionFieldHints
      );
    }
    return;
  }

  if (proxyVal && typeof proxyVal === 'object' && defaultsVal && typeof defaultsVal === 'object') {
    for (const key of Object.keys(proxyVal as Record<string, unknown>)) {
      extractTernaryConditionals(
        (proxyVal as Record<string, unknown>)[key],
        (defaultsVal as Record<string, unknown>)[key],
        result,
        optionalFieldNames,
        conditionFieldHints
      );
    }
  }
}

function extractTernaryConditionFieldHints(source: string): Map<string, string> {
  const hints = new Map<string, string>();
  const ternaryTemplatePattern =
    /spec\.([A-Za-z_$][\w$]*(?:\?\.[A-Za-z_$][\w$]*|\.[A-Za-z_$][\w$]*)*)\s*\?\s*`([\s\S]*?)`\s*:\s*(?:''|""|``)/g;
  let match: RegExpExecArray | null = ternaryTemplatePattern.exec(source);
  while (match) {
    const conditionField = normalizeSpecFieldPath(match[1]);
    const consequent = match[2] ?? '';
    if (conditionField) {
      const refPattern =
        /\$\{\s*spec\.([A-Za-z_$][\w$]*(?:\?\.[A-Za-z_$][\w$]*|\.[A-Za-z_$][\w$]*)*)/g;
      let refMatch: RegExpExecArray | null = refPattern.exec(consequent);
      while (refMatch) {
        const referencedField = normalizeSpecFieldPath(refMatch[1]);
        if (referencedField && !hints.has(referencedField)) {
          hints.set(referencedField, conditionField);
        }
        refMatch = refPattern.exec(consequent);
      }
    }
    match = ternaryTemplatePattern.exec(source);
  }
  return hints;
}

function normalizeSpecFieldPath(path: string | undefined): string | undefined {
  return path?.replace(/\?\./g, '.');
}

/**
 * Apply extracted nullish defaults to a KRO SimpleSchema spec fields object.
 * Appends `| default=<value>` to the field's type string.
 *
 * The two-phase default extraction uses this function twice:
 *   - Phase 1 (regex, `extractNullishDefaults`) — fast but may misfire on
 *     edge cases (multi-line expressions, nested parens). Called with
 *     `overwrite: false` so it doesn't clobber existing annotations.
 *   - Phase 2 (re-execution, `resolveDefaultsByReExecution`) — slower but
 *     authoritative. Called with `overwrite: true` so it REPLACES any
 *     Phase 1 annotation for the same field, ensuring a wrong Phase 1
 *     result doesn't survive when Phase 2 produces a corrected value.
 */
/**
 * Append a marker to a KRO SimpleSchema type string. KRO's format is `<type> | <m1> <m2> ...`: a SINGLE
 * `|` separates the type from a SPACE-separated marker block. So the FIRST marker is introduced with
 * ` | ` and every SUBSEQUENT marker with a space — emitting ` | ` between markers leaves a stray `|`
 * that KRO folds into the next marker's key (e.g. `enum="..." | default=` → unknown marker key `|default`,
 * which fails the OpenAPI schema build). Detecting an existing marker block via the ` | ` the type
 * already carries keeps single-marker fields (`string | default=...`) unchanged.
 */
function appendKroMarker(type: string, marker: string): string {
  return type.includes(' | ') ? `${type} ${marker}` : `${type} | ${marker}`;
}

/** Matches an existing `default=` marker in EITHER the pipe- or space-separated form, for replacement. */
const STRIP_DEFAULT_MARKER = /(?:\s*\|\s*|\s+)default=(?:"[^"]*"|[^|\s]*)/;

function applyNullishDefaults(
  specFields: Record<string, unknown>,
  defaults: Record<string, string | number | boolean>,
  overwrite = false
): void {
  for (const [path, value] of Object.entries(defaults)) {
    const parts = path.split('.');
    let current: Record<string, unknown> = specFields;

    for (let i = 0; i < parts.length - 1; i++) {
      const part = parts[i];
      if (!part) continue;
      if (current[part] && typeof current[part] === 'object') {
        current = current[part] as Record<string, unknown>;
      } else {
        current = undefined as unknown as Record<string, unknown>;
        break;
      }
    }

    if (!current) continue;

    const fieldName = parts[parts.length - 1];
    if (!fieldName) continue;
    const existingType = current[fieldName];
    if (typeof existingType !== 'string') continue;

    // Escape special characters in string defaults so they survive
    // the KRO SimpleSchema default= annotation format. Without this,
    // multiline strings (e.g., YAML config blobs) break the parser.
    const defaultStr = typeof value === 'string' ? `"${escapeCelString(value)}"` : String(value);
    const hasDefault = existingType.includes('default=');
    if (!hasDefault) {
      current[fieldName] = appendKroMarker(existingType, `default=${defaultStr}`);
    } else if (overwrite) {
      // Strip any existing `default=...` marker (pipe- OR space-separated form) and re-append the
      // authoritative Phase 2 value. The value may be `"x"`, `123`, or `true`.
      const withoutDefault = existingType.replace(STRIP_DEFAULT_MARKER, '');
      current[fieldName] = appendKroMarker(withoutDefault, `default=${defaultStr}`);
    }
  }
}

/**
 * Infer the KRO SimpleSchema type string for a literal default value.
 */
function kroTypeForLiteral(value: string | number | boolean): string {
  if (typeof value === 'string') {
    return `string | default="${escapeCelString(value)}"`;
  }
  if (typeof value === 'number') {
    return Number.isInteger(value) ? `integer | default=${value}` : `number | default=${value}`;
  }
  if (typeof value === 'boolean') {
    return `boolean | default=${value}`;
  }
  return 'string';
}

/**
 * For each default whose path doesn't exist in `specFields`, CREATE the
 * missing leaf (and any intermediate object nodes along the way) with
 * an appropriate KRO type string + default annotation.
 *
 * This is the complement to {@link applyNullishDefaults}, which only
 * annotates fields that already exist. Adding missing fields enables the
 * "propagate inner composition `?? defaults` to the outer schema"
 * mechanism: when an inner composition reads `spec.X?.Y ?? <literal>`
 * and the outer schema doesn't declare Y, we auto-declare it with the
 * inner's default so KRO can resolve the reference at apply time.
 *
 * **Scope rules:**
 *  - We only auto-create a missing field if EITHER the full path's parent
 *    already exists as an object in `specFields` (we're filling in a
 *    single missing leaf under a known object), OR the top-level parent
 *    (the first segment) doesn't exist at all (we're adding a whole new
 *    optional field). We do NOT create intermediate objects where the
 *    outer has explicitly declared a non-object type.
 *  - Existing fields are never modified — use `applyNullishDefaults`
 *    for that.
 */
function addMissingDefaultFields(
  specFields: Record<string, unknown>,
  defaults: Record<string, string | number | boolean>
): void {
  for (const [path, value] of Object.entries(defaults)) {
    const parts = path.split('.');
    if (parts.length === 0) continue;

    // Walk existing intermediate objects.
    let current: Record<string, unknown> = specFields;
    let i = 0;
    for (; i < parts.length - 1; i++) {
      const part = parts[i];
      if (!part) continue;
      const next = current[part];
      if (next && typeof next === 'object' && !Array.isArray(next)) {
        current = next as Record<string, unknown>;
      } else if (next === undefined) {
        // Create missing intermediate object node.
        const obj: Record<string, unknown> = {};
        current[part] = obj;
        current = obj;
      } else {
        // Intermediate path conflicts with an existing scalar — bail.
        current = undefined as unknown as Record<string, unknown>;
        break;
      }
    }
    if (!current) continue;

    const leafName = parts[parts.length - 1];
    if (!leafName) continue;
    if (leafName in current) continue; // existing — skip
    current[leafName] = kroTypeForLiteral(value);
  }
}

function remapDefaultPath(path: string, mappings: Record<string, string>): string | undefined {
  if (Object.hasOwn(mappings, '')) {
    const mappedPrefix = mappings[''];
    return mappedPrefix ? `${mappedPrefix}.${path}` : path;
  }

  const matches = Object.keys(mappings)
    .filter((prefix) => path === prefix || path.startsWith(`${prefix}.`))
    .sort((left, right) => right.length - left.length);

  const prefix = matches[0];
  if (prefix === undefined) return undefined;
  const mappedPrefix = mappings[prefix];
  if (mappedPrefix === undefined) return undefined;
  const suffix = path.slice(prefix.length);
  if (mappedPrefix === '') {
    return suffix.startsWith('.') ? suffix.slice(1) : suffix;
  }
  return `${mappedPrefix}${suffix}`;
}

function remapNullishDefaults(
  defaults: Record<string, string | number | boolean>,
  mappings: Record<string, string>
): Record<string, string | number | boolean> {
  const remapped: Record<string, string | number | boolean> = {};

  for (const [path, value] of Object.entries(defaults)) {
    const mappedPath = remapDefaultPath(path, mappings);
    if (mappedPath !== undefined) {
      remapped[mappedPath] = value;
    }
  }

  return remapped;
}

function schemaSpecMarker(path: string): string {
  return `__KUBERNETES_REF___schema___spec.${path}__`;
}

function remapTernaryConditionals(
  conditionals: TernaryConditional[],
  mappings: Record<string, string>
): TernaryConditional[] {
  return conditionals.flatMap((conditional) => {
    const conditionField = remapDefaultPath(conditional.conditionField, mappings);
    if (conditionField === undefined) return [];

    const proxySection = conditional.proxySection.replace(
      new RegExp(SCHEMA_MARKER_PATTERN_SOURCE, 'g'),
      (marker, fieldPath: string) => {
        if (!fieldPath.startsWith('spec.')) return marker;
        const remappedPath = remapDefaultPath(fieldPath.slice('spec.'.length), mappings);
        return remappedPath === undefined ? marker : schemaSpecMarker(remappedPath);
      }
    );

    return [{ ...conditional, conditionField, proxySection }];
  });
}

/**
 * Collect optional spec fields that don't have | default= annotations.
 * These fields need omit() wrapping in resource templates (KRO 0.9+)
 * so they're removed from the K8s resource when not provided, rather
 * than failing with an invalid zero value.
 *
 * Recurses into ALL object types so that both top-level optionals
 * (`env?`, `resources?`) and nested optionals (`database.storageClass?`,
 * `cache.replicas?`) are collected. Returns dotted field paths
 * (e.g., `['baseUrl', 'env', 'database.storageClass', 'cache', 'cache.replicas']`).
 *
 * **Both parent and children are tracked** when a whole object is
 * optional: if the user provides `cache: { shards: 1 }` (present but
 * with `replicas` absent), `has(cache)` is true and we must still
 * guard `cache.replicas` with its own omit. The ancestor resolution
 * in `maybeWrapWithOmit` prefers the deepest matching prefix, so a
 * ref to `cache.replicas` gets `has(cache.replicas) ? ... : omit()`
 * while a ref to `cache.shards` (required scalar with no default,
 * not in the set) falls back to the ancestor `cache` guard.
 */
function collectOmitFields(specFields: Record<string, unknown>, specType: Type): string[] {
  const omitFields: string[] = [];
  walk(specFields, specType.json, '');
  return omitFields;

  function walk(fields: Record<string, unknown>, node: unknown, pathPrefix: string): void {
    if (!node || typeof node !== 'object') return;
    const nodeObj = node as {
      optional?: { key: string; value: unknown }[];
      required?: { key: string; value: unknown }[];
    };
    const optionalKeys = new Set((nodeObj.optional ?? []).map((p) => p.key));
    const allEntries = [...(nodeObj.required ?? []), ...(nodeObj.optional ?? [])];

    for (const entry of allEntries) {
      const fieldName = entry.key;
      const fullPath = pathPrefix ? `${pathPrefix}.${fieldName}` : fieldName;
      const existingType = fields[fieldName];
      const isOptional = optionalKeys.has(fieldName);

      // Scalar optional without default → needs its own omit() guard.
      if (isOptional && typeof existingType === 'string' && !existingType.includes('default=')) {
        omitFields.push(fullPath);
        continue;
      }

      // Object (optional or required) → record the path if optional,
      // AND recurse to catch nested optional leaves. Even when the
      // object is required, its children may have their own optional
      // markers. Even when the object is optional, its children still
      // need their own guards because a present-but-sparse object
      // (e.g., `cache: { shards: 1 }` with `replicas` absent) must
      // not fail on ref-time `cache.replicas` access.
      if (typeof existingType === 'object' && existingType !== null) {
        if (isOptional) {
          omitFields.push(fullPath);
        }
        walk(existingType as Record<string, unknown>, entry.value, fullPath);
      }
    }
  }
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Convert an Arktype schema to a Kro-compatible schema definition.
 *
 * **Low-level**: accepts raw Arktype `Type` objects directly. For
 * type-safe usage with `SchemaDefinition`, prefer {@link generateKroSchemaFromArktype}.
 *
 * Status fields use user-defined mappings from the StatusBuilder function
 * instead of auto-generated CEL expressions.
 */
export function arktypeToKroSchema(
  name: string,
  schemaDefinition: {
    apiVersion: string;
    kind: string;
    group?: string;
    spec: Type;
    status: Type;
  },
  resources?: Record<string, KubernetesResource>,
  statusMappings?: Record<string, unknown>,
  nestedStatusCel?: Record<string, string>
): KroSimpleSchemaWithMetadata {
  const specFields = arktypeJsonToKroFields(schemaDefinition.spec.json);

  if (!specFields.name) {
    specFields.name = `string | default="${name}"`;
  }

  // Extract ?? defaults and add | default= annotations to the schema.
  // KRO uses these when a field isn't provided in the CR instance.
  //
  // Phase 1: fn.toString() regex — extracts literal ?? fallbacks quickly,
  //   for BOTH the outer composition AND every nested composition in the
  //   tree. See the nested-composition branch below for why.
  // Phase 2: Defaults resolution run — calls the composition function with
  //   undefined for optional fields, triggering ?? and resolving imported
  //   constants from the closure. Compares resolved resources with the
  //   proxy-run resources (markers) to extract field → default mappings.
  const statusMeta = statusMappings as Record<string, unknown> | undefined;
  const compositionFn = statusMeta?.__originalCompositionFn;

  // Phase 1a: regex extraction for the outer composition's own defaults.
  if (typeof compositionFn === 'function') {
    const regexDefaults = extractNullishDefaults(compositionFn.toString());
    applyNullishDefaults(specFields, regexDefaults);
    // Missing-field variant: also ADD any default path whose first
    // segment exists in specFields but whose full path doesn't. Handles
    // cases where the outer's own spec has `cache: { ... }` and reads
    // `spec.cache?.foo ?? bar` — the user expects `cache.foo` to be
    // optional with a default, but they forgot to declare it. We auto-
    // declare it for them.
    addMissingDefaultFields(specFields, regexDefaults);
  }

  // Phase 1b: regex extraction for every nested composition in the tree.
  //
  // When an inner composition uses `spec.X?.Y ?? <literal>` and the outer
  // passes its own `spec.X` proxy through (i.e., `innerComp({ X: spec.X, ... })`),
  // the inner's KRO-mode emission produces `${schema.spec.X.Y}` in the
  // flattened resource templates. The OUTER schema typically doesn't
  // declare Y — KRO rejects the RGD with "undefined field".
  //
  // We scan every nested composition's fn source for these `??` defaults
  // and ADD the missing fields to the outer specFields with the literal
  // as a KRO default. KRO then resolves the field using the default at
  // apply time, matching what direct-mode JS does via the `??` operator.
  //
  // This is the framework-side counterpart to the user workaround of
  // explicitly mirroring inner fields in the outer schema. It preserves
  // the "composition looks like native TypeScript" design goal — users
  // shouldn't have to repeat every inner schema detail.
  // `__nestedCompositionFns` was stored via Reflect.set. Read it via
  // getOwnPropertyDescriptor to bypass the Enhanced proxy's get-trap
  // (same pattern as `__nestedStatusCel`). The descriptor's value is
  // the real Map, not a proxy.
  const ternaryConditionals: TernaryConditional[] = [];
  const nestedFnsRaw = statusMappings
    ? Object.getOwnPropertyDescriptor(statusMappings, '__nestedCompositionFns')?.value
    : undefined;
  const nestedSpecMappingsRaw = statusMappings
    ? Object.getOwnPropertyDescriptor(statusMappings, '__nestedCompositionSpecMappings')?.value
    : undefined;
  const nestedDefinitionsRaw = statusMappings
    ? Object.getOwnPropertyDescriptor(statusMappings, '__nestedCompositionDefinitions')?.value
    : undefined;
  const nestedResourcesRaw = statusMappings
    ? Object.getOwnPropertyDescriptor(statusMappings, '__nestedCompositionResources')?.value
    : undefined;
  if (nestedFnsRaw instanceof Map) {
    for (const [baseId, fn] of nestedFnsRaw) {
      if (typeof fn !== 'function') continue;
      const specMappings =
        nestedSpecMappingsRaw instanceof Map ? nestedSpecMappingsRaw.get(baseId) : undefined;
      if (!specMappings || typeof specMappings !== 'object') continue;
      const extractedDefaults = extractNullishDefaults(fn.toString());
      const nestedDefinition =
        nestedDefinitionsRaw instanceof Map ? nestedDefinitionsRaw.get(baseId) : undefined;
      const nestedResources =
        nestedResourcesRaw instanceof Map ? nestedResourcesRaw.get(baseId) : undefined;
      const reExecutionResult =
        nestedDefinition && nestedResources
          ? resolveDefaultsByReExecution(
              fn as (...args: unknown[]) => unknown,
              nestedDefinition.spec,
              nestedResources
            )
          : undefined;
      const reExecutionDefaults = reExecutionResult?.defaults ?? {};
      const innerDefaults = remapNullishDefaults(
        { ...extractedDefaults, ...reExecutionDefaults },
        specMappings as Record<string, string>
      );
      // Non-destructive: don't overwrite existing outer defaults.
      applyNullishDefaults(specFields, innerDefaults, false);
      // Also add any fields the outer doesn't declare — the inner's
      // `?? <literal>` is the only signal we have that the field should
      // exist with a default.
      addMissingDefaultFields(specFields, innerDefaults);
      ternaryConditionals.push(
        ...remapTernaryConditionals(
          reExecutionResult?.ternaryConditionals ?? [],
          specMappings as Record<string, string>
        )
      );
    }
  }

  // Phase 2: resolve imported constants + detect ternary conditionals.
  // Phase 2 is AUTHORITATIVE — if it produces a value for a field that
  // Phase 1 also annotated, Phase 2 wins. This corrects Phase 1 misfires
  // on edge cases (multi-line expressions, nested parens) without breaking
  // the common case where both phases agree.
  if (typeof compositionFn === 'function' && resources) {
    const reExecutionResult = resolveDefaultsByReExecution(
      compositionFn as (...args: unknown[]) => unknown,
      schemaDefinition.spec,
      resources
    );
    if (reExecutionResult) {
      applyNullishDefaults(specFields, reExecutionResult.defaults, true);
      ternaryConditionals.push(...reExecutionResult.ternaryConditionals);
      // Cross-field `??` chains reconstructed by probing: write each CEL conditional
      // directly at its resource path (overwriting the bare head-field marker).
      for (const ov of reExecutionResult.crossFieldOverrides) {
        setAtResourcePath(resources[ov.resourceId], ov.path, ov.cel);
      }
    }
  }

  // Collect optional fields that DON'T have | default= after ?? extraction
  // AND aren't already handled by ternary conditionals.
  // These need omit() wrapping in resource templates (KRO 0.9+).
  const ternaryFieldNames = new Set(ternaryConditionals.map((t) => t.conditionField));
  const omitFields = collectOmitFields(specFields, schemaDefinition.spec).filter(
    (f) => !ternaryFieldNames.has(f)
  );

  // Filter internal fields (prefixed with __) before classification.
  // These are TypeKro metadata (e.g., __nestedStatusCel, __originalCompositionFn)
  // that should never appear in the KRO schema.
  const userStatusMappings: Record<string, unknown> = {};
  if (statusMappings) {
    for (const [key, value] of Object.entries(statusMappings)) {
      if (!key.startsWith('__')) {
        userStatusMappings[key] = value;
      }
    }
  }

  // Separate static and dynamic status fields.
  // Dynamic = references non-schema resource fields (status, metadata, spec) → KRO CEL
  // Static = references only schema.spec.* or literal values → TypeKro runtime hydration
  // Classification is transitive through nestedStatusCel: a nested composition
  // reference whose inner analyzed value is schema-only/literal is treated as static.
  const resourceIds = resources ? new Set(Object.keys(resources)) : undefined;
  const resourceAliases = resources ? new Map<string, string>() : undefined;

  if (resources && resourceAliases) {
    for (const [resourceId, resource] of Object.entries(resources)) {
      resourceAliases.set(resourceId, resourceId);
      for (const alias of deriveResourceIdAliases(resourceId)) {
        if (!resourceAliases.has(alias)) {
          resourceAliases.set(alias, resourceId);
        }
      }

      const aliases = getMetadataField(resource, 'resourceAliases') as string[] | undefined;
      if (aliases) {
        for (const alias of aliases) {
          resourceAliases.set(alias, resourceId);
        }
      }
    }
  }

  const { dynamicFields } = separateStatusFields(userStatusMappings, nestedStatusCel, resourceIds);

  const statusCelExpressions =
    Object.keys(dynamicFields).length > 0
      ? serializeStatusMappingsToCel(dynamicFields, nestedStatusCel, resourceIds, resourceAliases)
      : {};

  // Extract just the version part for the schema (Kro expects v1alpha1, not kro.run/v1alpha1)
  const schemaApiVersion = schemaDefinition.apiVersion.includes('/')
    ? schemaDefinition.apiVersion.split('/')[1] || schemaDefinition.apiVersion
    : schemaDefinition.apiVersion;
  const schemaGroup =
    schemaDefinition.group ??
    (schemaDefinition.apiVersion.includes('/')
      ? schemaDefinition.apiVersion.split('/')[0]
      : undefined);

  const schema: KroSimpleSchemaWithMetadata = {
    apiVersion: schemaApiVersion,
    kind: schemaDefinition.kind,
    ...(schemaGroup && { group: schemaGroup }),
    spec: specFields,
    status: {
      ...statusCelExpressions,
    },
  };

  // Attach metadata as non-enumerable properties — they're typed on
  // KroSimpleSchemaWithMetadata so consumers can read them without casts,
  // but non-enumerable so they don't appear in the schema YAML.
  if (ternaryConditionals.length > 0) {
    Object.defineProperty(schema, '__ternaryConditionals', {
      value: ternaryConditionals,
      enumerable: false,
    });
  }
  if (omitFields.length > 0) {
    Object.defineProperty(schema, '__omitFields', {
      value: omitFields,
      enumerable: false,
    });
  }

  return schema;
}

/**
 * Generate a minimal Kro schema from a resource map (no Arktype).
 *
 * Creates a schema with a default `name` spec field and an empty status.
 * Use this when you don't have Arktype type definitions. For typed schemas,
 * use {@link generateKroSchemaFromArktype} instead.
 */
export function generateKroSchema(
  name: string,
  _resources: Record<string, KubernetesResource>
): KroSimpleSchema {
  const pascalName = pascalCase(name);

  const spec: Record<string, string> = {
    name: `string | default="${name}"`,
  };

  return {
    apiVersion: `v1alpha1`,
    kind: pascalName,
    spec,
    status: {},
  };
}

/**
 * Generate a Kro schema from an Arktype-based `SchemaDefinition`.
 *
 * **Recommended** for most users. Accepts the same `SchemaDefinition` used
 * in `toResourceGraph()` and produces a flat Kro schema with properly
 * typed spec/status fields.
 *
 * @see {@link arktypeToKroSchema} for the low-level variant.
 * @see {@link generateKroSchema} for a simple variant without Arktype.
 */
export function generateKroSchemaFromArktype<
  TSpec extends KroCompatibleType,
  TStatus extends KroCompatibleType,
>(
  name: string,
  schemaDefinition: SchemaDefinition<TSpec, TStatus>,
  resources?: Record<string, KubernetesResource>,
  statusMappings?: Record<string, unknown>,
  nestedStatusCel?: Record<string, string>
): KroSimpleSchemaWithMetadata {
  return arktypeToKroSchema(name, schemaDefinition, resources, statusMappings, nestedStatusCel);
}
