/**
 * Bundle the HyperDX OIDC plugin (plugins/hyperdx-oidc) into one CommonJS file
 * and embed it in the library as a generated module.
 *
 * The bundle ships to clusters inside a ConfigMap, as `binaryData` (base64):
 * base64 keeps the JavaScript away from KRO's `${...}` template syntax, which
 * bundled code can contain.
 *
 *   bun run scripts/build-hyperdx-oidc-plugin.ts          # regenerate
 *   bun run scripts/build-hyperdx-oidc-plugin.ts --check  # fail if stale (CI)
 */

import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = join(import.meta.dir, '..');
const ENTRY = join(ROOT, 'plugins/hyperdx-oidc/src/index.ts');
const OUTPUT = join(ROOT, 'src/factories/clickstack/hyperdx-oidc/plugin-bundle.generated.ts');

const result = await Bun.build({
  entrypoints: [ENTRY],
  target: 'node',
  format: 'cjs',
  minify: true,
});
if (!result.success) {
  for (const message of result.logs) console.error(message);
  process.exit(1);
}
// Bundled third-party code keeps its license notice (MIT requires it in copies).
const oauthLicense = readFileSync(join(ROOT, 'node_modules/oauth4webapi/LICENSE.md'), 'utf8').trim();
const banner =
  '/*! TypeKro HyperDX OIDC plugin — https://github.com/yehudacohen/typekro (Apache-2.0)\n' +
  ` * Bundles oauth4webapi (https://github.com/panva/oauth4webapi):\n * ${oauthLicense.replace(/\*\//g, '* /').split('\n').join('\n * ')}\n */\n`;
const code = banner + (await (result.outputs[0] as Blob).text());
const bytes = Buffer.from(code, 'utf8');
const sha256 = createHash('sha256').update(bytes).digest('hex');

const generated = `// GENERATED by scripts/build-hyperdx-oidc-plugin.ts from plugins/hyperdx-oidc — DO NOT EDIT.
// Regenerate with: bun run scripts/build-hyperdx-oidc-plugin.ts

/**
 * The bundled HyperDX OIDC plugin (CommonJS), base64-encoded. Typed \`string\`
 * on purpose: a literal type would copy the whole bundle into the \`.d.ts\`.
 */
export const HYPERDX_OIDC_PLUGIN_BASE64: string =
  '${bytes.toString('base64')}';

/** SHA-256 of the decoded bundle; changes whenever the plugin does. */
export const HYPERDX_OIDC_PLUGIN_SHA256: string = '${sha256}';

/** Size of the decoded bundle in bytes. */
export const HYPERDX_OIDC_PLUGIN_BYTES: number = ${bytes.length};
`;

if (process.argv.includes('--check')) {
  let current = '';
  try {
    current = readFileSync(OUTPUT, 'utf8');
  } catch {}
  if (current !== generated) {
    console.error(
      `${OUTPUT} is stale. Run: bun run scripts/build-hyperdx-oidc-plugin.ts`
    );
    process.exit(1);
  }
  console.log(`hyperdx-oidc plugin bundle is current (${bytes.length} bytes, sha256 ${sha256.slice(0, 12)})`);
} else {
  writeFileSync(OUTPUT, generated);
  console.log(`wrote ${OUTPUT} (${bytes.length} bytes, sha256 ${sha256.slice(0, 12)})`);
}
